# step 1
FROM node:18.10 AS build
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm install
COPY . /app
RUN npm run build -- --output-path=./dist/out
#step 2
FROM nginx:latest
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build app/dist/out/ /usr/share/nginx/html